WEBSOCKET wss://ws.bitstamp.net/
Content-Type: application/json

{
  "event":"bts:subscribe",
  "data": {
    "channel":"live_trades_ethbtc"
  }
}

###

GET https://www.bitstamp.net/api/v2/markets/
Accept: application/json

###

GET https://www.bitstamp.net/api/v2/ticker/
Accept: application/json

###

GET https://www.bitstamp.net/api/v2/ticker/ethbtc/
Accept: application/json
