# curl -i http://localhost:8080/prices/BTC-USD
GET http://localhost:8080/prices/BTC-USD
Accept: application/json

###

# curl -i http://localhost:8080/prices/ETH-USD
GET http://localhost:8080/prices/ETH-USD
Accept: application/json

###

# curl -i http://localhost:8080/prices/ETH-BTC
GET http://localhost:8080/prices/ETH-BTC
Accept: application/json

###

# This request always returns 404. This symbol was not configured.

# curl -i http://localhost:8080/prices/BTC-USD
GET http://localhost:8080/prices/BTC-ETH
Accept: application/json

###
